options:
  docker: true
pipelines:
  custom:
    deploy-to-test:
      - step:
          name: Build and Upload
          image:
            name: beblue/aws:ecs
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWORD
          caches:
            - docker
          script:
            - upload --repository "beblue/logger-service"
      - step:
          name: Deploy to Test
          image:
            name: beblue/aws:ecs
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWORD
          deployment: test
          script:
            - deploy --environment "test" --nodes 1
  branches:
    develop:
      - step:
          name: Build and Upload
          image:
            name: beblue/aws:ecs
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWORD
          caches:
            - docker
          script:
            - upload --repository "beblue/logger-service"
      - step:
          name: Deploy to Develop
          image:
            name: beblue/aws:ecs
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWORD
          deployment: staging
          trigger: manual
          script:
            - deploy --environment "staging" --nodes 1
    master:
      - step:
          name: Build and Upload
          image:
            name: beblue/aws:ecs
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWORD
          caches:
            - docker
          script:
            - upload --repository "beblue/logger-service"
      - step:
          name: Deploy to Production
          image:
            name: beblue/aws:ecs
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWORD
          deployment: production
          trigger: manual
          script:
            - deploy --environment "production" --nodes 2
