options:
  docker: true
pipelines:
  custom:
    deploy-to-test:
      - step:
          name: Build and Upload
          image:
            name: beblue/aws:ecs
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWORD
          caches:
            - docker
          script:
            - upload --repository "beblue/logger-service"
      - step:
          name: Deploy to Test
          image:
            name: beblue/aws:ecs
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWORD
          deployment: test
          script:
            - deploy --environment "test" --nodes 1
    deploy-data-science-test:
      - step:
          name: Build and Upload
          image:
            name: beblue/aws:ecs
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWORD
          caches:
            - docker
          script:
            - upload --repository "beblue/logger-service"
      - step:
          name: Deploy to Test
          image:
            name: beblue/aws:ecs
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWORD
          deployment: test
          script:
            - deploy --strategy "rolling" --environment "test" --repository "beblue/logger-service" --stack "beblue/logger-service"
  branches:
    develop:
      - step:
          name: Build and Upload
          image:
            name: beblue/aws:ecs
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWORD
          caches:
            - docker
          script:
            - upload --repository "beblue/logger-service"
      - step:
          name: Deploy to Develop
          image:
            name: beblue/docker:cloud
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWORD
          deployment: test
          script:
            - deploy --strategy "rolling" --environment "test" --repository "beblue/logger-service" --stack "beblue/logger-service"
    master:
      - step:
          name: Build and Upload
          image:
            name: beblue/aws:ecs
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWORD
          caches:
            - docker
          script:
            - upload --repository "beblue/logger-service"
      - step:
          name: Deploy to Production
          image:
            name: beblue/docker:cloud
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWORD
          deployment: production
          trigger: manual
          script:
            - deploy --strategy "rolling" --environment "production" --repository "beblue/logger-service" --stack "beblue/logger-service"
