version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  postgres:
    driver: ${VOLUMES_DRIVER}

services:
  logger-service:
    image: logger-service-local
    restart: always
    volumes:
#      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ./:/logger-service
#    volumes:
#      - /home/phakiller/.aws/credentials:/root/.aws/credentials
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - database
    ports:
      - "${WORKSPACE_SSH_PORT}:22"
#      - "${WORKSPACE_APP_PORT}:8000"
      - "8000:8000"
    networks:
      - frontend
      - backend
  database:
    image: postgres
    restart: always
    volumes:
      - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - backend