# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-22 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(null=False, max_length=100)),
                ('merchant_id', models.CharField(null=False, max_length=10)),
                ('hotdeal', models.BooleanField(null=False, default=False)),
                ('promocode', models.BooleanField(null=False, default=False)),
                ('created_at', models.DateTimeField(null=False, auto_now_add=True)),
            ]
        ),
        migrations.AddIndex('Event', models.Index(fields=['user_id'], name='idx_evt_user_id')),
        migrations.AddIndex('Event', models.Index(fields=['merchant_id'], name='idx_evt_merchant_id')),
        migrations.AddIndex('Event', models.Index(fields=['created_at'], name='idx_evt_created_at'))
    ]
